### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by nero120**

### CODE REVIEW

**Comment by tomaasz** [comment]
Could you add support for fill SyncID and password by LastPass ?

**Comment by tomaasz** [comment]
Could you add History synchronization ?

**Comment by tomaasz** [comment]
I would make Polish translation of I would know how to do this

**Comment by nero120** [comment]
@tomaasz check out the [wiki](https://github.com/xbrowsersync/app/wiki/Translations).

**Pull request merged**
